# Environment Settings
gpu_id: '0, 1, 2, 3, 4, 5, 6, 7'
use_gpu: True
workers: 2

# Model Settings
embedding_size: 64

# Data Settings
load_col:                       # (dict) The suffix of atomic files: (list) field names to be loaded.
    inter: [user_id, item_id, rating, timestamp]
# Training Settings
epochs: 300
train_batch_size: 8192
train_neg_sample_args:
  distribution: uniform
  sample_num: 1
  alpha: 1.0
  dynamic: False
  candidate_num: 0
valid_metric: MRR@10
eval_step: 5

# Evaluation Settings
eval_batch_size: 40960
eval_args:
  group_by: user
  order: TO
  split: {RS: [0.8, 0.1, 0.1]}
  mode: uni100
metric_decimal_place: 4
topk: 10

# Zipf Settings
zipf_alpha: 0.94

# Entropy settings
entropy_alpha: 0.7
